In [2]:
import numpy as np
np.__version__

'1.26.4'

# 배열 연산

In [1]:
import numpy as np

a = np.arange(3)
a

array([0, 1, 2])

In [2]:
print(a+2)
print(a-2)
print(a*2)
print(a/2)

[2 3 4]
[-2 -1  0]
[0 2 4]
[0.  0.5 1. ]


In [4]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
b = np.full_like(a, [1,2,3])
b

array([[1, 2, 3],
       [1, 2, 3]])

In [6]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[2 4 6]
 [5 7 9]]
[[0 0 0]
 [3 3 3]]
[[ 1  4  9]
 [ 4 10 18]]
[[1.  1.  1. ]
 [4.  2.5 2. ]]


In [7]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [8]:
b = np.arange(0.5, 4, 1)
b

array([0.5, 1.5, 2.5, 3.5])

In [11]:
# a += b
# a의 원소 자료형은 int인데 저장할 결과는 float라서 발생하는 문제

In [9]:
b += a

In [3]:
a = np.full((2,3),[1,2,3])
a

array([[1, 2, 3],
       [1, 2, 3]])

In [4]:
b = np.full((3,2),[2,1])
b

array([[2, 1],
       [2, 1],
       [2, 1]])

In [5]:
a @ b

array([[12,  6],
       [12,  6]])

In [6]:
a.dot(b)

array([[12,  6],
       [12,  6]])

In [7]:
b.dot(a)

array([[3, 6, 9],
       [3, 6, 9],
       [3, 6, 9]])

In [12]:
a = np.array([[10,20],[5,8],[1,2]])
a

array([[10, 20],
       [ 5,  8],
       [ 1,  2]])

In [8]:
a.sum()

12

In [9]:
a.sum(axis=0)

array([2, 4, 6])

In [10]:
a.sum(axis=1)

array([6, 6])

In [13]:
import numpy as np

print(np.sum(a))
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

46
[16 30]
[30 13  3]


In [14]:
a = np.array([[3, 5, 8],[1, 2, 3]])
a

array([[3, 5, 8],
       [1, 2, 3]])

In [15]:
a.cumsum()

array([ 3,  8, 16, 17, 19, 22])

In [16]:
a.cumsum(axis=0)

array([[ 3,  5,  8],
       [ 4,  7, 11]])

In [17]:
a.cumsum(axis=1)

array([[ 3,  8, 16],
       [ 1,  3,  6]])

In [18]:
import numpy as np

a = np.array([1, 4, 9])
np.sqrt(a)

array([1., 2., 3.])

In [19]:
np.log(a)

array([0.        , 1.38629436, 2.19722458])

In [20]:
import numpy as np

a = np.array([1, 4, 9])
a

array([1, 4, 9])

In [21]:
b = np.full_like(a, 2)
b

array([2, 2, 2])

In [22]:
np.add(a,b)

array([ 3,  6, 11])

In [23]:
np.divide(a,b)

array([0.5, 2. , 4.5])

In [24]:
np.power(a,b)

array([ 1, 16, 81])

# 배열 슬라이싱과 형태 수정

In [25]:
import numpy as np

a = np.power(np.arange(10),2)
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [26]:
print(a[3])
print(a[-2])

9
64


In [27]:
print(a[1:4])
print(a[-5:-1])

[1 4 9]
[25 36 49 64]


In [29]:
print(a[8:2:-1])
print(a[-1:-7:-1])

[64 49 36 25 16  9]
[81 64 49 36 25 16]


In [30]:
a[::-1]
a[::-2]

array([81, 49, 25,  9,  1])

In [31]:
a[2:5]
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [32]:
a[2:5] = -100
a

array([   0,    1, -100, -100, -100,   25,   36,   49,   64,   81])

In [33]:
a[2:5] = [-5, -5, -5]
a

array([ 0,  1, -5, -5, -5, 25, 36, 49, 64, 81])

In [35]:
#a[2:5] = [-5, -5]
#a
#오류

In [36]:
b = np.array([5] * 10)
b

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [37]:
b[::2] = -10
b

array([-10,   5, -10,   5, -10,   5, -10,   5, -10,   5])

In [40]:
b[::2] = -10
b

array([-10,   5, -10,   5, -10,   5, -10,   5, -10,   5])

In [41]:
b[::2] = np.arange(5)
b

array([0, 5, 1, 5, 2, 5, 3, 5, 4, 5])

In [42]:
a = np.arange(30).reshape(5,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [43]:
a[3]

array([18, 19, 20, 21, 22, 23])

In [44]:
a[-1]

array([24, 25, 26, 27, 28, 29])

In [45]:
a[-2, :]

array([18, 19, 20, 21, 22, 23])

In [46]:
a[-2, :]

array([18, 19, 20, 21, 22, 23])

In [47]:
a[2 : 4]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [48]:
a[1:5:2]

array([[ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])

In [49]:
a[:, 1]

array([ 1,  7, 13, 19, 25])

In [52]:
a[:, 1:6]

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23],
       [25, 26, 27, 28, 29]])

In [53]:
a[:, ::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [54]:
a[2,4]

np.int64(16)

In [55]:
a[2][4]

np.int64(16)

In [56]:
a[1:3, 2:5]

array([[ 8,  9, 10],
       [14, 15, 16]])

In [57]:
a[:, :]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [58]:
a[::-1, ::-1]

array([[29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

In [59]:
#마지막 행과 열을 제외한 배열 반환
a[:-1, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16],
       [18, 19, 20, 21, 22]])

### 3차원 배열의 첨자와 슬라이싱

In [61]:
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [62]:
a[:, 1, 1]

array([ 5, 17])

In [63]:
a[:, :, 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [64]:
a[..., 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [65]:
a[1, ..., 1]

array([13, 17, 21])

In [66]:
a[0, ...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### 배열 형태 수정

In [68]:
a = np.arange(12).reshape(2,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [69]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [71]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [74]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [75]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [76]:
np.transpose(a, (0,1))

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
np.transpose(a, (1,0))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [79]:
b = np.arange(1,13).reshape(3,2,2)
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [80]:
b.T

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [82]:
np.transpose(b, (0,1,2)) #b 그대로

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [88]:
np.transpose(b, (2,1,0)) #b.T와 같음

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [89]:
np.transpose(b, (0,2,1)) #1축과 2축을 서로 바꾼 정치 행렬

array([[[ 1,  3],
        [ 2,  4]],

       [[ 5,  7],
        [ 6,  8]],

       [[ 9, 11],
        [10, 12]]])

In [86]:
c = np.arange(1,13).reshape(2,2,3)
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [87]:
c.transpose((1,2,0))

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

In [91]:
x = np.array([[7,8,9]])
x

array([[7, 8, 9]])

In [93]:
y = np.swapaxes(x, 0, 1)
y

array([[7],
       [8],
       [9]])