In [2]:
import numpy as np
np.__version__

'1.26.4'

In [3]:
from numpy import arange

x = arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
y = arange(-1, 2)
y

array([-1,  0,  1])

In [6]:
x * y

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

In [7]:
x + y

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [8]:
from numpy import arange

x = arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
y = arange(3,10,3).reshape(3,1)
y

array([[3],
       [6],
       [9]])

In [11]:
x / y

array([[0.33333333, 0.66666667, 1.        ],
       [0.66666667, 0.83333333, 1.        ],
       [0.77777778, 0.88888889, 1.        ]])

In [12]:
x - y

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

In [13]:
from numpy import arange

x = arange(1,4)
x

array([1, 2, 3])

In [14]:
y = arange(1,4).reshape(3,1)
y

array([[1],
       [2],
       [3]])

In [15]:
x * y

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [16]:
x - y

array([[ 0,  1,  2],
       [-1,  0,  1],
       [-2, -1,  0]])

In [17]:
from numpy import arange
x = arange(0,10,3).reshape(4,1)
x

array([[0],
       [3],
       [6],
       [9]])

In [18]:
y = arange(1,3)
y

array([1, 2])

In [19]:
x * y

array([[ 0,  0],
       [ 3,  6],
       [ 6, 12],
       [ 9, 18]])

In [20]:
x + y

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [21]:
from numpy import array

x = array([0,10,20,30])
x

array([ 0, 10, 20, 30])

In [22]:
a = x[None, :]
a

array([[ 0, 10, 20, 30]])

In [23]:
a = x[np.newaxis, :]
a

array([[ 0, 10, 20, 30]])

In [24]:
a = x[:,np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [25]:
from numpy import array

b = array([1,2,3])
b

array([1, 2, 3])

In [26]:
a + b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [29]:
a * b

array([[ 0,  0,  0],
       [10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [30]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
print(x[1])
print(x[:5])

1
[0 1 2 3 4]


In [32]:
print(x[[2]])
print(x[[2,3]])

[2]
[2 3]


## 4장 다차원 배열 결합과 분리

hstack() vstack()

In [33]:
import numpy as np

a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [34]:
b = np.arange(6,12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [35]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [36]:
c = np.arange(20,24).reshape(2,2)
c

array([[20, 21],
       [22, 23]])

In [37]:
np.vstack((a,c))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [20, 21],
       [22, 23]])

In [38]:
np.vstack((a,b,c))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [20, 21],
       [22, 23]])

In [39]:
d = np.array([100,200])
np.vstack((a,d))

array([[  0,   1],
       [  2,   3],
       [  4,   5],
       [100, 200]])

In [41]:
d = np.array([100,200,300])
#np.vstack((a,d)) #오류

In [43]:
import numpy as np

x = np.array([1,2,3])
y = np.array([5,6,7])
np.vstack((x,y))

array([[1, 2, 3],
       [5, 6, 7]])

In [3]:
import numpy as np

a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [4]:
b = np.arange(10,19).reshape(3,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [5]:
np.hstack((a,b))

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

In [6]:
c = np.array([[10,20], [30,40]])
c

array([[10, 20],
       [30, 40]])

In [8]:
#np.hstack((a,c))
# 오류 / 수평으로 합칠 수 없음

In [9]:
np.hstack((np.arange(3), np.arange(10,15)))

array([ 0,  1,  2, 10, 11, 12, 13, 14])

### 배열 결합 연산 column_stack()과 row_stack()

In [10]:
import numpy as np
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [11]:
b = np.arange(10,22).reshape(3,4)
b

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [13]:
np.column_stack((a,b)) #np.hstack((a,b))와 동일

array([[ 0,  1, 10, 11, 12, 13],
       [ 2,  3, 14, 15, 16, 17],
       [ 4,  5, 18, 19, 20, 21]])

In [14]:
x = np.array([1,2,3])
y = np.array([10,20,30])
np.column_stack((x,y))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [15]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [16]:
y[:, np.newaxis]

array([[10],
       [20],
       [30]])

In [17]:
x = np.array([1,2,3])
y = np.array([10,20,30])
np.column_stack((x[:, np.newaxis], y[:, np.newaxis]))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [18]:
np.hstack((x,y)) #결론 : 1차원에서 np.hstack()과 np.column_stack()은 결과가 다르다!

array([ 1,  2,  3, 10, 20, 30])

In [19]:
np.column_stack == np.hstack

False

In [20]:
import numpy as np
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
b = np.arange(10,22).reshape(4,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [22]:
np.row_stack((a,b)) #np.vstack()와 기능이 같다

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [23]:
np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [24]:
a = np.array([4., 2., 1.])
b = np.array([3., 8., 7.])
print(np.row_stack((a,b)))

[[4. 2. 1.]
 [3. 8. 7.]]


In [25]:
print(np.vstack((a,b)))

[[4. 2. 1.]
 [3. 8. 7.]]


In [26]:
np.row_stack == np.vstack #결론 : np.row_stack과 np.vstack의 결과는 항상 같다!

True

### 배열 결합 연산 concatenate()와 stack()

In [27]:
import numpy as np

a = np.array([1,2])
b = np.array([3,4])
c = np.array([5,6])

In [29]:
np.concatenate((a,b,c))

array([1, 2, 3, 4, 5, 6])

In [30]:
np.concatenate((a,b,c), axis=0)

array([1, 2, 3, 4, 5, 6])

In [32]:
np.concatenate((a,b,c), axis=None)

array([1, 2, 3, 4, 5, 6])

In [33]:
import numpy as np

x = np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [35]:
y = np.arange(10,16).reshape(2,3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [36]:
z = np.arange(20,24).reshape(2,2)
z

array([[20, 21],
       [22, 23]])

In [37]:
np.concatenate((x,y))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [39]:
#np.concatenate((x,y,z))
#오류 : 열 수가 다른 z는 수직으로 합칠 수 없다.

In [40]:
np.concatenate((x,y), axis=1) # 축 1로 합치므로 수평으로 합쳐진다.

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

In [41]:
np.concatenate((x,y,z),axis=1)

array([[ 0,  1,  2, 10, 11, 12, 20, 21],
       [ 3,  4,  5, 13, 14, 15, 22, 23]])

In [42]:
np.concatenate((x,y), axis=None)

array([ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 15])

In [49]:
import numpy as np

a = np.array([1,2,3])
a

array([1, 2, 3])

In [50]:
b = np.array([4,5,6])
b

array([4, 5, 6])

In [45]:
np.stack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
np.stack((a,b),axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [53]:
np.stack((a,b), axis=-1) # -1은 마지막 축을 의미한다

array([[1, 4],
       [2, 5],
       [3, 6]])

In [54]:
x = np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [55]:
y = np.arange(10,16).reshape(2,3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [56]:
z = np.arange(20,26).reshape(2,3)
z

array([[20, 21, 22],
       [23, 24, 25]])

In [57]:
ax0 = np.stack((x,y,z), axis=0)
ax0

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[10, 11, 12],
        [13, 14, 15]],

       [[20, 21, 22],
        [23, 24, 25]]])

In [58]:
ax0.shape

(3, 2, 3)

In [60]:
ax1 = np.stack((x,y,z), axis=1)
ax1

array([[[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22]],

       [[ 3,  4,  5],
        [13, 14, 15],
        [23, 24, 25]]])

In [62]:
ax1.shape

(2, 3, 3)

In [63]:
ax2 = np.stack((x,y,z), axis=2)
ax2

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [64]:
ax2.shape

(2, 3, 3)

### 배열의 결합 비교

In [65]:
import numpy as np

a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [68]:
c = np.arange(1,6,2)
c

array([1, 3, 5])

In [69]:
c[:, np.newaxis]

array([[1],
       [3],
       [5]])

In [70]:
np.hstack((a, c[:, np.newaxis]))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [73]:
#np.hstack((a,c)) 
#오류 : np.hstack() 함수 호출로 바로 수평으로 합칠 수 없다. 위처럼 2차원으로 확장해 호출해야 한다.

In [75]:
np.hstack((a, np.expand_dims(c, axis=1)))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [76]:
np.column_stack((a,c))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [77]:
import numpy as np

a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [78]:
b = np.arange(1,5)
b

array([1, 2, 3, 4])

In [79]:
np.row_stack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [80]:
np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

### np.c_[]

In [81]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

result = np.c_[a,b]
print(result)
# 주요 용도 : 데이터를 칼럼 단위로 결합할 때 편리하게 사용, 1차원 배열들을 2차원 배열로 변환하는 기능을 지원하므로, 머신러닝이나 데이터 분석에서 종종 사용

[[1 4]
 [2 5]
 [3 6]]


In [82]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

In [83]:
np.c_[a,b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [84]:
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [91]:
x = np.array([[1,2,3]])
y = np.array([[4,5,6]])

np.c_[x,y]

array([[1, 2, 3, 4, 5, 6]])

In [92]:
np.column_stack((x,y))

array([[1, 2, 3, 4, 5, 6]])

In [93]:
np.c_[x, 10,20,y]

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [94]:
np.column_stack((x,10,20,y))

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [95]:
np.r_[3:10:3, [0]*2, 5,6]

array([3, 6, 9, 0, 0, 5, 6])

In [97]:
np.r_[-1:1:6j, [0]*2, 5,6] #-1에서 1사이에서 실수 6개로 등분하는 실수 시퀀스 반환

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ,  0. ,  0. ,  5. ,  6. ])

In [99]:
np.linspace(-1, 1, 6)

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ])